version: "3.8"

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: flask-backend
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads  # persists uploads
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: react-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules # persists node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - CHOKIDAR_USEPOLLING=true  # Helps hot reload in Docker
      - REACT_APP_API_BASE=http://localhost:5000
    restart: unless-stopped


# Usage:

# 1. Build the images:
# docker-compose build

# 2. Run the containers:
# docker-compose up -d